name: jeffharris
favicon: null
layout_spectrum: 0.4490199249703437
typography_spectrum: 0.6655708854086697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.13176413578912616
  lightness: 0.8094828615430743
  saturation: 0.938292755978182
  rhythmicContrast: 0.37861083960160613
purpose: []
